### ISSUE TITLE
Prevent characters from being escaped

### ISSUE THREAD

**Issue by broughtupsy** [zwbetz-gh/hugo-client-side-search-template#15]
I wanted to change the URL param from `query` to `campaign=search&ref` (for goatcounter tracking) but the characters `=` and `&` are being escaped in the browser. How to prevent this?

**Comment by zwbetz-gh** [comment]
The character escaping is intentional, as some characters don't play nice in the URL bar. Think of space characters, etc. 

If you wanted to disable this, you edit these lines:

Remove the `encodeURIComponent`:
https://github.com/zwbetz-gh/hugo-client-side-search-template/blob/67af96298fbf5557f237ab409b1f195c837c6777/assets/js/main.ts#L63

Remove the `decodeURIComponent`:
https://github.com/zwbetz-gh/hugo-client-side-search-template/blob/67af96298fbf5557f237ab409b1f195c837c6777/assets/js/main.ts#L55

**Comment by broughtupsy** [comment]
Do I need to remove that exact code (I tried, didn't work) or even the code after?

**Comment by zwbetz-gh** [comment]
If you want to change the param name from `query` to `campaign` then do this.
Patch file and equivalent screenshot are attached. 

[issue-15.patch.zip](https://github.com/zwbetz-gh/hugo-client-side-search-template/files/14953152/issue-15.patch.zip)

<img width="1726" alt="Screenshot 2024-04-11 at 9 03 18 PM" src="https://github.com/zwbetz-gh/hugo-client-side-search-template/assets/37317628/3299de76-832c-4219-8634-24deeedeae69">

**Comment by zwbetz-gh** [comment]
lol. Spaces in a URL are not valid. 
I hope you're able to find that which you seek. Good luck.
