### ISSUE TITLE
Search missing some terms

### ISSUE THREAD

**Issue by bapps2** [zwbetz-gh/hugo-client-side-search-template#6]
The search misses entries with words if they are not at the beginning of the term. For example, terms beginning with `puroresu` will show up when `puroresu` is typed, but `tokyo joshi puroresu company` will not show up in that list. Can this be rectified?

**Comment by zwbetz-gh** [comment]
I cannot reproduce this. 

For example, I searched the demo site for `rover` and got many hits with words at the end of the string.

https://hugo-client-side-search-template.netlify.app/?query=rover

Screenshot:

![screencapture-hugo-client-side-search-template-netlify-app-2023-01-02-21_36_04](https://user-images.githubusercontent.com/37317628/210297134-6997a2b9-e887-46a2-aec5-2053e10ee61e.png)

**Comment by bapps2** [comment]
Here is an example with real data. I searched for the word "Neema" in a 10,000 JSON entries data set.
1. Result https://prnt.sc/_5nL2xzbAAdZ
2. Missing from the list https://prnt.sc/K5oAEQGlqSZG (As you can see, it has the word "Neema" in it).

**Comment by zwbetz-gh** [comment]
I still cannot reproduce this. We can only speculate since you didn't provide a [minimal reproducible sample](https://stackoverflow.com/help/minimal-reproducible-example).

One idea is to increase the max hits shown:

https://github.com/zwbetz-gh/hugo-client-side-search-template/blob/67af96298fbf5557f237ab409b1f195c837c6777/assets/js/main.ts#L15

Another idea is to confirm these Fuse.js options are set:

https://github.com/zwbetz-gh/hugo-client-side-search-template/blob/67af96298fbf5557f237ab409b1f195c837c6777/assets/js/main.ts#L28-L29

**Comment by bapps2** [comment]
`const MAX_HITS_SHOWN = 10;` Increasing that solved it.

**Comment by zwbetz-gh** [comment]
Very good.
